from pygame.locals import *

# Configuration

KEY_UP = (K_z, K_UP)
KEY_DOWN = (K_s, K_DOWN)
KEY_LEFT = (K_q, K_LEFT)
KEY_RIGHT = (K_d, K_RIGHT)

SQUARE_SIZE = 16
SQUARE_COUNT = 20
WINDOW_HEIGHT = SQUARE_SIZE * SQUARE_COUNT
WINDOW_WIDTH = SQUARE_SIZE * SQUARE_COUNT
TARGET_FPS = 60
WINDOW_TITLE = 'Pysnake!'
BACKGROUND_COLOR = (159, 207, 159)
SNAKE_COLOR = (0, 0, 0)
SNAKE_HEAD_COLOR = (255, 0, 0)
FOOD_COLOR = (0, 0, 0)
TILES_BORDER = 1
SPEED_EASY = 400
SPEED_NORMAL = 200
SPEED_HARD = 100
SPEED_NIGHTMARE = 50
SNAKE_START_LEN = 4 
FOOD_FREQUENCY = 0.3
FOOD_TTL = 6
DIRECTION_EST = (1, 0)
DIRECTION_NORTH = (0, -1)
DIRECTION_WEST = (-1, 0)
DIRECTION_SOUTH = (0, 1)

